executor: KubernetesExecutor

images:
  airflow:
    repository: gshernandez481/airflow
    tag: "e59d6de"
    pullPolicy: IfNotPresent

config:
  logging:
    remote_logging: "True"
    remote_base_log_folder: "s3://airflow-logs"
    remote_log_conn_id: "airflow_logs"

data:
  metadataSecretName: airflow-metadata
  metadataConnection:
    user: airflow
    protocol: postgresql
    host: airflow-postgres
    port: 5432
    db: airflow

postgresql:
  enabled: false
redis:
  enabled: false

flower:
  enabled: false

logs:
  persistence:
    enabled: false

ingress:
  enabled: false

scheduler:
  replicas: 1
  resources:
    requests: { cpu: 200m, memory: 512Mi }
    limits:   { cpu: 500m, memory: 1Gi }
  startupProbe:
    timeoutSeconds: 60
    periodSeconds: 20
    failureThreshold: 10
  livenessProbe:
    timeoutSeconds: 60
    periodSeconds: 60
    failureThreshold: 10

webserver:
  replicas: 1
  resources:
    requests: { cpu: 100m, memory: 256Mi }
    limits:   { cpu: 300m, memory: 512Mi }
  defaultUser:
    enabled: true
    username: "admin"

triggerer:
  replicas: 1
  resources:
    requests: { cpu: 200m, memory: 512Mi }
    limits:   { cpu: 500m, memory: 1Gi }
  livenessProbe:
    timeoutSeconds: 60
    periodSeconds: 60
    failureThreshold: 10

workers:
  podTemplate: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: placeholder-name
    spec:
      containers:
        - name: base
          envFrom:
            - secretRef:
                name: airflow-s3-conn
